---
### Backend ###
backend_src_dir: '{{ deploy_src_dir }}/backend'

### Django ###
django_dir: '{{ backend_src_dir }}'
django_app_name: 'deepmed'
django_wsgi_file: '{{ django_dir }}/{{ django_app_name }}/wsgi.py'
django_settings: '{{ django_app_name }}.settings'
django_static_url: '/static'
django_static_root: '{{ django_dir }}/static'
django_media_url: '/media'
django_media_root: '{{ django_dir }}/media'
django_fixtures: # Path to fixture file. Example: '{{ django_dir }}/fixtures/initial.json
  - '{{ django_dir }}/fixtures/initial_data.json'


### Django channels ###
django_channels_daphne_host: 127.0.0.1                    # Local address to bind
django_channels_daphne_port: 8085


### Local settings ###
debug: False
django_local_settings_file: '{{ django_dir }}/{{ django_app_name }}/local_settings.py'
secret_key: '{{ vaulted_secret_key }}'

database_host: 'localhost'
database_port: '{{ postgresql_port }}'
database_name: '{{ vaulted_database_name }}'
database_user: '{{ vaulted_database_user }}'
database_password: '{{ vaulted_database_password }}'


### Python ###
python_ppa: 'ppa:jonathonf/python-3.6'
python_versions:
  - 3.6
python_install: []
python_virtualenvs:
  - path: '{{ virtualenv_dir }}'
    python: python3.6


### PIP requirements ###
pip_requirements:
  - '{{ django_dir }}/requirements.txt'


### Virtualenv ###
virtualenv_dir: '{{ deploy_dir }}/venv'
