---
- src: Stouts.deploy
  version: 1.2.0

- src: kamaln7.swapfile

- src: Stouts.apt
  version: 1.4.0

- src: ANXS.hostname
  version: v1.1.0

- src: ANXS.ntp
  version: v1.1.0

- src: ANXS.git
  version: v1.0.1

- src: Stouts.python
  version: 2.2.0

- src: ANXS.apt
  version: v1.3.0

- src: ANXS.build-essential
  version: v1.0.2

- src: git+https://github.com/erik-moroz/postgresql.git
  version: ff850b8571798b2338275d5674f1b890fe1408d4
  name: ANXS.postgresql

- src: jdauphant.nginx
  version: v2.9

- src: geerlingguy.nodejs
  version: 4.1.1

- src: ocha.yarn
  version: v1.1.0

- src: erik-moroz.Supervisor
  version: v1.0.0

- src: franklinkim.environment

- src: git+https://github.com/m-kalyna/Stouts.celery.git
  version: c50857937042b729d8ac86f8ae210ef2e0081225
  name: Stouts.celery

- src: DavidWittman.redis
  version: 1.2.4