---
- name: Configure application server
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: kamaln7.swapfile
      become: true
      tags: [common]

    - role: Stouts.deploy
      become: true
      tags: [common]

    - role: Stouts.apt
      become: true
      tags: [common]

    - role: ANXS.hostname
      become: true
      tags: [common]

    - role: ANXS.ntp
      become: yes
      tags: [common]

    - role: ANXS.git
      become: true
      tags: [common]

    - role: Stouts.python
      become: true
      tags: [common]

    - role: erik-moroz.Supervisor
      become: true
      tags: [supervisor]

    - role: ANXS.postgresql
      become: true
      tags: [database]

#    - role: mongodb
#      become: true
#      when: run_mongo
#      tags: [mongo]

    - role: DavidWittman.redis
      become: true
      tags: [cache]

    - role: jdauphant.nginx
      become: true
      tags: [project]

    - role: gunicorn
      become: true
      tags: [gunicorn]

    - role: geerlingguy.nodejs
      become: true
      tags: [project]

    - role: ocha.yarn
      become: true
      tags: [project]

    - role: franklinkim.environment
      become: true
      tags: [project]

    - role: Stouts.celery
      become: true
      tags: [celery]

    - role: webtier
      tags: [webtier]
